// ═══════════════════════════════════════════════════════════════
// ares-lang.js — AresPipe Merkezi Çeviri Modülü
// Yeni dil eklemek için bu dosyaya yeni bir blok ekleyin.
// Sayfalarda _I18N, tv(), _applyI18n() tanımlamayın.
// ═══════════════════════════════════════════════════════════════
(function(w) {
  'use strict';

  // ── Tüm Dil Verileri ────────────────────────────────────────
  var _LANG = {
    // ── Türkçe (varsayılan — fallback olarak kullanılır) ──────
    tr: {},   // TR için ayrı çeviri gerekmez; fallback TR metni sayfa içindedir

    // ── İngilizce ─────────────────────────────────────────────
    en: {
      bk_belge_eklendi: 'document(s) added',
      bk_belge_secildi: 'selected — Excel import coming soon',
      bk_bend_len_hint: 'Pipe length that can be bent',
      bk_bend_len_label: 'Bend Length (mm)',
      bk_bend_progress: 'Bending Progress',
      bk_bent_done_label: 'Bent',
      bk_bent_label: 'Bent',
      bk_boru_duzenle: 'Edit Pipe',
      bk_boru_ekle: 'Add Pipe',
      bk_boru_eklendi: 'Pipe added',
      bk_boru_silindi: 'Pipe deleted',
      bk_breadcrumb: 'Bending',
      bk_btn_apply: 'Apply',
      bk_btn_back: '← Back',
      bk_btn_bent: '✓ Bent',
      bk_btn_bent_done: '✓ Bent',
      bk_btn_clear: 'Clear',
      bk_btn_close: 'Close',
      bk_btn_ekle: 'Add',
      bk_btn_guncelle: 'Update',
      bk_btn_iptal: 'Cancel',
      bk_btn_new_fason: '+ New Job Order Bending',
      bk_btn_reset: '↺ Reset',
      bk_btn_template: '⬇ Template',
      bk_btn_upload: '⬆ Upload',
      bk_col_action: 'Action',
      bk_col_bend_date: 'Bend Date',
      bk_col_date: 'Date',
      bk_col_diam: 'Diameter',
      bk_col_firm: 'Firm',
      bk_col_grade: 'Grade',
      bk_col_isemir: 'Work Order',
      bk_col_isemir_fb: 'Work Order / FB No',
      bk_col_len: 'Bend Length',
      bk_col_mat: 'Material',
      bk_col_no: '#',
      bk_col_pipes: 'Pipes',
      bk_col_progress: 'Progress',
      bk_col_qr: 'QR',
      bk_col_spool: 'Spool No',
      bk_col_spoolid: 'Spool ID',
      bk_col_status: 'Status',
      bk_col_thk: 'Thickness',
      bk_col_yard: 'Yard',
      bk_confirm_desc: 'This pipe will be removed from the list and processed.',
      bk_confirm_title: 'Bending Complete?',
      bk_confirm_yes: 'Yes, Bent',
      bk_csv_indir: 'CSV template downloaded',
      bk_done_title: 'Completed Bending',
      bk_dosya_no_gir: 'Enter file number',
      bk_empty_done: 'No bent pipes yet',
      bk_empty_fason: 'No job order bending files',
      bk_empty_pending: 'No pipes awaiting bending',
      bk_excel_indir: 'Excel template downloaded',
      bk_fason_dosyasi: 'Job Order Bending File',
      bk_fason_files: 'Job Order Bending Files',
      bk_fason_title: 'Job Order Bending',
      bk_filter_all: 'All',
      bk_filter_diam: 'Diameter',
      bk_filter_fason_src: 'Job Order',
      bk_filter_grade: 'Grade',
      bk_filter_isemir: 'Work Order',
      bk_filter_kaynak: 'Source',
      bk_filter_mat: 'Material',
      bk_filter_source: 'Source',
      bk_filter_spool: 'Spool',
      bk_filter_thk: 'Thickness',
      bk_firma_sec: 'Please select a company',
      bk_fm_cap: 'Diameter (mm)',
      bk_fm_kalinlik: 'Thickness (mm)',
      bk_fm_kalite: 'Grade',
      bk_fm_malzeme: 'Material',
      bk_footer_boru: 'pipes',
      bk_footer_toplam: 'Total:',
      bk_home: 'Home',
      bk_mal_sec: 'Please select material',
      bk_new_fason_hint: 'Click the New Job Order Bending button',
      bk_new_fason_modal: '📄 New Job Order Bending',
      bk_nf_aciklama: 'Description (optional)',
      bk_nf_aciklama_ph: 'Short description...',
      bk_nf_belge_ekle: '+ Add Document',
      bk_nf_belge_yukle: 'Upload Document (optional)',
      bk_nf_dosya_no: 'File Number',
      bk_nf_firma: 'Company',
      bk_nf_firma_sec: 'Select company...',
      bk_nf_olustur: '✓ Create File',
      bk_no_belge: 'No documents yet',
      bk_no_boru_hint: 'No pipes yet — click Add Pipe button',
      bk_no_fason: 'No job order bending files yet',
      bk_olcu_gir: 'Enter a valid length',
      bk_olusturuldu: 'created',
      bk_page_title: 'Bending Management',
      bk_pg_next: 'Next →',
      bk_pg_prev: '← Prev',
      bk_qr_title: 'QR — Bending Pipe',
      bk_search_ph: 'Spool no, job order no, material...',
      bk_select_all: 'Select All',
      bk_sil_btn: 'Yes, Delete',
      bk_sil_desc: 'This action cannot be undone.',
      bk_sil_title: 'Delete Pipe?',
      bk_stat_done: 'Bent',
      bk_stat_fason: 'Job Orders',
      bk_stat_pending: 'Pending',
      bk_stat_projects: 'Our Projects',
      bk_stat_total: 'Total Bends',
      bk_tab_done: 'Bent',
      bk_tab_fason: 'Job Order Bending',
      bk_tab_pending: 'Pending',
      cmn_anasayfa: 'Home',
      cmn_onceki: 'Previous',
      cmn_sonraki: 'Next',
      cmn_yenile: 'Refresh',
      idx_btn_adet: 'Count',
      idx_btn_kg: 'Weight',
      idx_cal_calendars: 'Calendars',
      idx_cal_dblclick: '· Double-click to add a note',
      idx_cal_legend: 'Days with events',
      idx_cal_no_event: 'no events',
      idx_cal_search: 'Search events...',
      idx_cal_today: 'Today',
      idx_dow: ['Mo','Tu','We','Th','Fr','Sa','Su'],
      idx_ev_musteri: 'Customer',
      idx_ev_not: 'Note',
      idx_ev_personel: 'Personnel',
      idx_ev_proje: 'Project',
      idx_grp_cikis: 'CONTROL & DISPATCH',
      idx_grp_uretim: 'PRODUCTION',
      idx_lbl_total_adet: 'TOTAL COUNT',
      idx_lbl_total_kg: 'TOTAL WEIGHT',
      idx_loading: 'Loading...',
      idx_mat_alu: 'Aluminum',
      idx_mat_celik: 'Steel',
      idx_mat_cunife: 'Cunife',
      idx_mat_pas: 'Stainless',
      idx_mat_tumu: 'All',
      idx_mo: ['January','February','March','April','May','June','July','August','September','October','November','December'],
      idx_spool_title: 'Total Spool Status in System',
      idx_stage_bekleyen: 'PENDING',
      idx_stage_imalat: 'FABRICATION',
      idx_stage_kalite: 'QUALITY',
      idx_stage_kaynak: 'WELDING',
      idx_stage_on_kontrol: 'PRE-INSPECT',
      idx_stage_sevke_hazir: 'READY',
      idx_stat_devre: 'Active Circuits',
      idx_stat_kesim: 'Cutting Pending',
      idx_stat_kk: 'QC Pending',
      idx_stat_proje: 'Active Projects',
      idx_stat_sevk: 'Shipped This Month',
      idx_sys_label: 'Shipyard Management System',
      idx_title: 'Dashboard',
      kk_all: 'All',
      kk_approve_all: 'Approve All',
      kk_breadcrumb: 'Quality Control',
      kk_btn_clear: 'Clear',
      kk_btn_create_invite: 'Create Invitation Package',
      kk_cancel: 'Cancel',
      kk_card_control: 'Control:',
      kk_card_invite: 'Invite:',
      kk_contact_note: 'Contact / Note',
      kk_control_date: 'Estimated Control Date',
      kk_control_date_label: 'Control Date',
      kk_controller: 'Controller',
      kk_create_save: 'Create & Save Package',
      kk_davet_circuit: 'Circuit:',
      kk_davet_spool: 'Spool:',
      kk_davet_total: 'Total:',
      kk_decision: 'Decision',
      kk_durum_bekle: 'Awaiting Yard',
      kk_durum_onay: 'Approved',
      kk_durum_ret: 'Rejected / Correction',
      kk_empty_bekle: 'No pending invitation packages',
      kk_empty_onay: 'No approved packages yet',
      kk_empty_spool: 'No spools to display',
      kk_enter_approval: 'Enter Approval',
      kk_extra_note: 'Additional Note',
      kk_filter_all_projects: 'All Projects',
      kk_filter_all_yards: 'All Yards',
      kk_filter_clear: 'Clear',
      kk_filter_proj: 'All Projects',
      kk_filter_yard: 'All Yards',
      kk_home: 'Home',
      kk_invite_date: 'Invitation Date',
      kk_mail: 'Email',
      kk_mail_optional: '(optional)',
      kk_modal_approve_title: 'Enter Quality Approval',
      kk_modal_invite_title: 'Create Quality Invitation Package',
      kk_no_approved: 'No approved packages yet',
      kk_no_pending: 'No pending invitation packages',
      kk_no_spool: 'No spools to display',
      kk_optional: 'Optional...',
      kk_pdf_btn: 'PDF',
      kk_pdf_preview: 'Preview PDF',
      kk_reject: 'Reject / Correction',
      kk_reject_ph: 'Which spools were rejected, what corrections are needed?',
      kk_reject_reason: 'Rejection Reason',
      kk_save_approval: 'Save Approval',
      kk_search_ph: 'Search circuit or spool...',
      kk_sec_clear: 'Clear',
      kk_sec_create: 'Create Invitation Package',
      kk_sec_devre: 'Circuit',
      kk_sec_kg: 'kg',
      kk_sec_spool: 'Spool',
      kk_secili: ' selected',
      kk_select_all: 'Select All',
      kk_selected_spools: 'Selected Spools',
      kk_sevkiyata: 'To Shipment →',
      kk_spool_col: 'Spool',
      kk_stat_approved: 'Approved',
      kk_stat_bekle: 'Awaiting Yard',
      kk_stat_davet: 'Invitation Package',
      kk_stat_hazir: 'Ready for QC',
      kk_stat_invite: 'Invitation Package',
      kk_stat_onay: 'Approved',
      kk_stat_ready: 'Ready for QC',
      kk_stat_waiting: 'Awaiting Yard',
      kk_status_approved: 'Approved',
      kk_status_pending: 'Awaiting Yard',
      kk_status_rejected: 'Rejected / Correction',
      kk_tab_bekle: 'Pending',
      kk_tab_bekleyen: 'Pending',
      kk_tab_davet: 'Create Invitation',
      kk_tab_onay: 'Approved',
      kk_tab_onaylanan: 'Approved',
      kk_title: 'Quality Control',
      kk_to_shipment: 'To Shipment →',
      kk_toast_approved_ship: 'approved — ready for shipment!',
      kk_toast_controller_req: 'Controller name is required',
      kk_toast_created: 'invitation package created',
      kk_toast_date_req: 'Date is required',
      kk_toast_decision_req: 'Please select a decision',
      kk_toast_invite_date_req: 'Invitation date is required',
      kk_toast_karar: 'Please select a decision',
      kk_toast_kisi: 'Controller name is required',
      kk_toast_olusturuldu: 'invitation package created',
      kk_toast_onaylandi: 'approved — ready for shipment!',
      kk_toast_pdf: 'PDF downloading...',
      kk_toast_pdf_soon: 'PDF preview coming soon',
      kk_toast_reject_req: 'Rejection reason is required',
      kk_toast_rejected: 'rejected',
      kk_toast_ret_neden: 'Rejection reason is required',
      kk_toast_ret_sonuc: 'rejected',
      kk_toast_select_first: 'Please select spools first',
      kk_toast_sevkiyat: 'PDF downloading...',
      kk_toast_shipment: 'Added to shipment preparation list',
      kk_toast_tarih: 'Date is required',
      kk_tumu: 'All',
      kk_weight_col: 'Weight',
      ks_at_least_one: 'At least 1 record must be checked',
      ks_breadcrumb: 'Cutting Management',
      ks_btn_apply: 'Apply',
      ks_btn_clear: 'Clear',
      ks_btn_create: '📋 Create Cutting List',
      ks_btn_form: '📂 Cutting Form',
      ks_btn_markall: '☑ Mark All',
      ks_btn_reset: '↺ Reset',
      ks_btn_save_close: '✓ Save & Close List',
      ks_btn_unmarkall: '☐ Unmark All',
      ks_chip_cap: 'Diameter',
      ks_chip_cert: 'Certificate',
      ks_chip_cert_no: 'Uncertified',
      ks_chip_cert_yes: 'Certified',
      ks_chip_grade: 'Grade',
      ks_chip_isemir: 'Work Order',
      ks_chip_mat: 'Material',
      ks_chip_search: 'Search',
      ks_chip_thk: 'Thickness',
      ks_chip_yard: 'Yard',
      ks_col_action: 'Action',
      ks_col_cap: 'Diameter',
      ks_col_cut: 'Cut (mm)',
      ks_col_cut_done: 'Cut',
      ks_col_grade: 'Grade',
      ks_col_isemir: 'Work Order',
      ks_col_mat: 'Material',
      ks_col_sert: 'Cert.',
      ks_col_spool: 'Spool No',
      ks_col_spoolid: 'Spool ID',
      ks_col_thk: 'Thickness',
      ks_col_uca: 'End A',
      ks_col_ucb: 'End B',
      ks_col_yard: 'Yard',
      ks_created: 'created',
      ks_cut_label: 'cut',
      ks_cut_progress: 'Cutting progress',
      ks_done_header: '✓ Cut Lists',
      ks_downloaded: 'downloaded',
      ks_empty_hint: 'Change filter or search criteria',
      ks_empty_notfound: 'No records found',
      ks_excel_err: 'Excel error:',
      ks_excel_ready: 'Excel being prepared...',
      ks_filter_cert: 'Certificate',
      ks_filter_cert_no: 'Uncertified',
      ks_filter_cert_yes: 'Certified',
      ks_filter_diam: 'Diameter',
      ks_filter_grade: 'Grade',
      ks_filter_isemir: 'Work Order',
      ks_filter_mat: 'Material',
      ks_filter_thk: 'Thickness',
      ks_filter_yard: 'Yard',
      ks_footer_boru: 'pipes · Page',
      ks_footer_total: 'Total:',
      ks_form_addstok: '+ Add Pipe Section',
      ks_form_cancel: 'Cancel',
      ks_form_kerf: 'Saw Kerf (mm)',
      ks_form_minartik: 'Min Usable Remnant (mm)',
      ks_form_parcaboru: 'Available Pipe Sections — optional, mm',
      ks_form_run: '✂ Generate Form & Download',
      ks_form_stok: 'Standard Stock Length (mm)',
      ks_form_trim: 'End Trim (mm)',
      ks_geri_dondu: 'returned',
      ks_home: 'Home',
      ks_kesim_tamamlandi: 'cut completed',
      ks_kismi: 'partial',
      ks_lists_header: '📋 Cutting Lists',
      ks_modal_cut_btn: '✓ Yes, Cut',
      ks_modal_cut_cancel: 'Cancel',
      ks_modal_cut_desc: 'This pipe will be removed from the list and processed.',
      ks_modal_cut_title: 'Cutting Complete?',
      ks_modal_list_cancel: 'Cancel',
      ks_modal_list_cap: 'Diameter:',
      ks_modal_list_create: '✓ Create List',
      ks_modal_list_hint: 'Leave empty for auto numbering.',
      ks_modal_list_mat: 'Material:',
      ks_modal_list_no: 'List Number',
      ks_modal_list_title: '📋 Create Cutting List',
      ks_modal_list_total: 'Total Cut:',
      ks_modal_list_yard: 'Yard:',
      ks_no_arc: 'No completed records yet',
      ks_no_lists: 'No cutting lists created yet',
      ks_no_lists_hint: 'Create a list from the Cutting Pending tab',
      ks_no_single: 'No individual cuts yet',
      ks_page_title: '✂ Cutting Management',
      ks_search_ph: 'Spool no, work order, material...',
      ks_select_all: 'Select All',
      ks_single_header: '⚡ Individual Cuts',
      ks_stat_filtered: 'Filtered',
      ks_stat_inlist: 'In List',
      ks_stat_pending: 'Total Pending',
      ks_tab_done: '✓ Cut Lists',
      ks_tab_lists: '📋 Cutting Lists',
      ks_tab_pending: '✂ Cutting Pending',
      ks_tab_single: '⚡ Individual Cuts',
      ks_tamamlandi: 'completed',
      log_ara_placeholder: '🔍 Search operation, source, description…',
      log_baslik: 'Operation Log',
      log_csv_indir: 'Download CSV',
      log_csv_indirildi: 'CSV downloaded',
      log_f_ay: 'This Month',
      log_f_bugun: 'Today',
      log_f_devre: '🔄 Circuit',
      log_f_giris: '🔐 Login',
      log_f_hafta: 'This Week',
      log_f_is: '🔧 Work',
      log_f_kk: '✅ Quality Control',
      log_f_sevk: '📦 Shipment',
      log_f_spool: '⚙️ Spool',
      log_f_tanim: '📋 Definition',
      log_f_test: '🧪 Test',
      log_f_tum_islem: 'All Operations',
      log_f_tum_zaman: 'All Time',
      log_gecmis: 'Operation History',
      log_gorunum_tablo: 'Table',
      log_gorunum_zaman: 'Timeline',
      log_il_devre_durdur: 'Circuit Stopped',
      log_il_giris: 'Login',
      log_il_is_baslat: 'Work Started',
      log_il_is_bitir: 'Work Completed',
      log_il_kk_gonder: 'QC Submitted',
      log_il_kk_onayla: 'QC Approved',
      log_il_kk_red: 'QC Rejected',
      log_il_sevk: 'Shipment',
      log_il_spool_durdur: 'Spool Stopped',
      log_il_tanim_ekle: 'Definition Added',
      log_il_tanim_sil: 'Definition Deleted',
      log_il_kesim_tamamla: 'Cutting Completed',
      log_il_kesim_eklendi: 'Cutting Added',
      log_il_kesim_liste: 'Cutting List Saved',
      log_il_bukum_tamamla: 'Bending Completed',
      log_il_bukum_eklendi: 'Bending Added',
      log_il_mrk_tamamla: 'Marking Completed',
      log_il_mrk_eklendi: 'Marking Added',
      log_il_kk_davet: 'QC Invitation Created',
      log_il_kk_onay: 'QC Approval Saved',
      ts_baslik: 'Tests',
      ts_stat_bekleyen: 'Pending', ts_stat_devam: 'In Progress',
      ts_stat_tamamlanan: 'Completed', ts_stat_hatali: 'Failed / Repair',
      ts_stat_toplam: 'Total Packages',
      ts_tab_bekleyen: 'Pending', ts_tab_devam: 'In Progress',
      ts_tab_tamamlanan: 'Completed', ts_tab_hepsi: 'All Tests',
      ts_btn_yeni: 'New Test', ts_btn_sonuc: 'Enter Result',
      ts_f_tum_tip: 'All Test Types', ts_f_tum_tersane: 'All Yards',
      ts_ara_ph: 'Test no, circuit, project...',
      ts_modal_yeni: 'New Test Package', ts_modal_sonuc: 'Enter Test Result',
      ts_modal_tip: 'Test Types',
      ts_durum_bekleyen: 'Waiting', ts_durum_devam: 'In Progress',
      ts_durum_tamamlandi: 'Completed ✓', ts_durum_hatali: 'Failed / Repair',
      ts_kart_tarih: 'Date:', ts_kart_yetkili: 'Inspector:',
      ts_gecti: 'passed', ts_hatali: 'failed', ts_bekliyor: 'waiting',
      ts_spool_sonuclari: 'Spool Results',
      ts_bos: 'No tests to display',
      ts_pdf_indir: 'PDF downloading...',
      ts_toast_kod_ad: 'Code and name are required',
      ts_toast_kod_var: 'This code already exists',
      ts_toast_sonuc: ' test result saved',
      ts_toast_tip_eklendi: ' test type added',
      cmn_temizle: 'Clear',

      log_il_test_olustur: 'Test Created',
      log_il_test_sonuc: 'Test Result',
      log_kayit_bulunamadi: 'No records found',
      log_kayit_sayisi: ' records',
      log_stat_bugun: 'Today',
      log_stat_kullanici: 'Users',
      log_stat_tip: 'Operation Types',
      log_stat_toplam: 'Total Records',
      log_temizle: 'Clear Log',
      log_temizle_onay: 'All log records will be deleted. Are you sure?',
      log_temizlendi: 'Log cleared',
      log_th_aciklama: 'DESCRIPTION',
      log_th_islem: 'OPERATION',
      log_th_kaynak: 'SOURCE',
      log_th_kullanici: 'USER',
      log_th_no: '#',
      log_th_zaman: 'TIME',
      log_yenilendi: 'Refreshed',
      mk_arc_header: '✓ Completed Lists',
      mk_arc_title: 'Archive',
      mk_at_least_one: 'At least 1 record must be checked',
      mk_breadcrumb: 'Marking Management',
      mk_btn_apply: 'Apply',
      mk_btn_clear: 'Clear',
      mk_btn_create: '🏷 Create Marking List',
      mk_btn_excel: '📂 Download Excel',
      mk_btn_markall: '☑ Mark All',
      mk_btn_reset: '↺ Reset',
      mk_btn_save_close: '✓ Save & Close List',
      mk_btn_unmarkall: '☐ Unmark All',
      mk_chip_cap: 'Diameter',
      mk_chip_isemir: 'Work Order',
      mk_chip_kalite: 'Grade',
      mk_chip_parca: 'Part',
      mk_chip_search: 'Search',
      mk_chip_tersane: 'Yard',
      mk_col_action: 'Action',
      mk_col_cap: 'Diameter',
      mk_col_done: 'Done',
      mk_col_isemir: 'Work Order',
      mk_col_malzeme: 'Material',
      mk_col_parca: 'Part Name',
      mk_col_spool: 'Spool No',
      mk_col_spoolid: 'Spool ID',
      mk_col_yard: 'Yard',
      mk_created: 'created',
      mk_empty_hint: 'Change filter or search criteria',
      mk_empty_notfound: 'No records found',
      mk_filter_diam: 'Diameter',
      mk_filter_grade: 'Grade',
      mk_filter_isemir: 'Work Order',
      mk_filter_mat: 'Material',
      mk_filter_parca: 'Part',
      mk_filter_yard: 'Yard',
      mk_footer_record: 'records · Page',
      mk_geri_dondu: 'returned',
      mk_home: 'Home',
      mk_indirildi: 'downloaded',
      mk_kismi: 'partial',
      mk_lists_header: '🗒 Marking Lists',
      mk_lists_title: 'Created Lists',
      mk_manuel_iptal: 'Cancel',
      mk_manuel_title: 'Manuel İşaretlenenler',
      mk_marked: 'marked',
      mk_modal_list_cancel: 'Cancel',
      mk_modal_list_cap: 'Diameter:',
      mk_modal_list_create: '✓ Create List',
      mk_modal_list_hint: 'Leave empty for auto numbering.',
      mk_modal_list_kayit: 'Records:',
      mk_modal_list_no: 'List Number',
      mk_modal_list_parca: 'Part:',
      mk_modal_list_tersane: 'Yard:',
      mk_modal_list_title: '🏷 Create Marking List',
      mk_modal_mark_btn: '✓ Yes, Marked',
      mk_modal_mark_desc: 'Was this part manually marked?',
      mk_modal_mark_title: 'Mark as Labelled',
      mk_modal_warn_desc: 'Selected records must have the same part name and diameter.',
      mk_modal_warn_ok: 'OK, I will fix the filter',
      mk_modal_warn_retry: 'Retry with same criteria',
      mk_modal_warn_title: 'Cannot Create List',
      mk_no_arc: 'No completed records yet',
      mk_no_lists: 'No marking lists created yet',
      mk_page_title: '✂ Marking Management',
      mk_plaka: 'Plate',
      mk_progress_label: 'Marking progress',
      mk_search_ph: 'Spool no, work order, material...',
      mk_select_all: 'Select All',
      mk_serbest: 'Free marking',
      mk_stat_filtered: 'Filtered',
      mk_stat_inlist: 'In List',
      mk_stat_pending: 'Total Pending',
      mk_tab_done: 'Completed',
      mk_tab_lists: 'Marking Lists',
      mk_tab_pending: 'Pending Marking',
      mk_tamamlandi: 'completed',
    },

    // ── Arapça ────────────────────────────────────────────────
    ar: {
      bk_belge_eklendi: 'مستند(ات) أضيفت',
      bk_belge_secildi: 'محدد — استيراد Excel قريباً',
      bk_bend_len_hint: 'طول الأنبوب الذي يمكن ثنيه',
      bk_bend_len_label: 'طول الثني (مم)',
      bk_bend_progress: 'تقدم الثني',
      bk_bent_done_label: 'مثني',
      bk_bent_label: 'مثني',
      bk_boru_duzenle: 'تعديل أنبوب',
      bk_boru_ekle: 'إضافة أنبوب',
      bk_boru_eklendi: 'تم إضافة الأنبوب',
      bk_boru_silindi: 'تم حذف الأنبوب',
      bk_breadcrumb: 'الثني',
      bk_btn_apply: 'تطبيق',
      bk_btn_back: '← رجوع',
      bk_btn_bent: '✓ تم الثني',
      bk_btn_bent_done: '✓ تم الثني',
      bk_btn_clear: 'مسح',
      bk_btn_close: 'إغلاق',
      bk_btn_ekle: 'إضافة',
      bk_btn_guncelle: 'تحديث',
      bk_btn_iptal: 'إلغاء',
      bk_btn_new_fason: '+ ثني أمر جديد',
      bk_btn_reset: '↺ إعادة',
      bk_btn_template: '⬇ قالب',
      bk_btn_upload: '⬆ رفع',
      bk_col_action: 'الإجراء',
      bk_col_bend_date: 'تاريخ الثني',
      bk_col_date: 'التاريخ',
      bk_col_diam: 'القطر',
      bk_col_firm: 'الشركة',
      bk_col_grade: 'الجودة',
      bk_col_isemir: 'أمر العمل',
      bk_col_isemir_fb: 'أمر / FB',
      bk_col_len: 'طول الثني',
      bk_col_mat: 'المادة',
      bk_col_no: '#',
      bk_col_pipes: 'الأنابيب',
      bk_col_progress: 'التقدم',
      bk_col_qr: 'QR',
      bk_col_spool: 'رقم البكرة',
      bk_col_spoolid: 'معرف البكرة',
      bk_col_status: 'الحالة',
      bk_col_thk: 'السماكة',
      bk_col_yard: 'الحوض',
      bk_confirm_desc: 'سيتم إزالة هذا الأنبوب من القائمة ومعالجته.',
      bk_confirm_title: 'اكتمل الثني؟',
      bk_confirm_yes: 'نعم، تم الثني',
      bk_csv_indir: 'تم تنزيل قالب CSV',
      bk_done_title: 'الثني المكتمل',
      bk_dosya_no_gir: 'أدخل رقم الملف',
      bk_empty_done: 'لا توجد أنابيب مثنية بعد',
      bk_empty_fason: 'لا توجد ملفات ثني أوامر',
      bk_empty_pending: 'لا توجد أنابيب في انتظار الثني',
      bk_excel_indir: 'تم تنزيل قالب Excel',
      bk_fason_dosyasi: 'ملف ثني أمر',
      bk_fason_files: 'ملفات ثني الأوامر',
      bk_fason_title: 'ثني الأوامر',
      bk_filter_all: 'الكل',
      bk_filter_diam: 'القطر',
      bk_filter_fason_src: 'أمر',
      bk_filter_grade: 'الجودة',
      bk_filter_isemir: 'أمر العمل',
      bk_filter_kaynak: 'المصدر',
      bk_filter_mat: 'المادة',
      bk_filter_source: 'المصدر',
      bk_filter_spool: 'بكرة',
      bk_filter_thk: 'السماكة',
      bk_firma_sec: 'الرجاء اختيار شركة',
      bk_fm_cap: 'القطر (مم)',
      bk_fm_kalinlik: 'السماكة (مم)',
      bk_fm_kalite: 'الجودة',
      bk_fm_malzeme: 'المادة',
      bk_footer_boru: 'أنابيب',
      bk_footer_toplam: 'المجموع:',
      bk_home: 'الرئيسية',
      bk_mal_sec: 'الرجاء اختيار مادة',
      bk_new_fason_hint: 'انقر على زر إنشاء ثني أمر جديد',
      bk_new_fason_modal: '📄 ثني أمر جديد',
      bk_nf_aciklama: 'وصف (اختياري)',
      bk_nf_aciklama_ph: 'وصف قصير...',
      bk_nf_belge_ekle: '+ إضافة مستند',
      bk_nf_belge_yukle: 'رفع مستند (اختياري)',
      bk_nf_dosya_no: 'رقم الملف',
      bk_nf_firma: 'الشركة',
      bk_nf_firma_sec: 'اختر شركة...',
      bk_nf_olustur: '✓ إنشاء الملف',
      bk_no_belge: 'لا توجد مستندات بعد',
      bk_no_boru_hint: 'لا توجد أنابيب بعد — انقر زر إضافة أنبوب',
      bk_no_fason: 'لا توجد ملفات ثني بعد',
      bk_olcu_gir: 'أدخل طولاً صحيحاً',
      bk_olusturuldu: 'تم الإنشاء',
      bk_page_title: 'إدارة الثني',
      bk_pg_next: 'التالي →',
      bk_pg_prev: '← السابق',
      bk_qr_title: 'QR — أنبوب الثني',
      bk_search_ph: 'رقم البكرة، أمر العمل، المادة...',
      bk_select_all: 'تحديد الكل',
      bk_sil_btn: 'نعم، احذف',
      bk_sil_desc: 'لا يمكن التراجع عن هذا الإجراء.',
      bk_sil_title: 'حذف الأنبوب؟',
      bk_stat_done: 'مثني',
      bk_stat_fason: 'أوامر العمل',
      bk_stat_pending: 'قيد الانتظار',
      bk_stat_projects: 'مشاريعنا',
      bk_stat_total: 'إجمالي الثني',
      bk_tab_done: 'مثني',
      bk_tab_fason: 'ثني الأوامر',
      bk_tab_pending: 'قيد الانتظار',
      cmn_anasayfa: 'الرئيسية',
      cmn_onceki: 'السابق',
      cmn_sonraki: 'التالي',
      cmn_yenile: 'تحديث',
      idx_btn_adet: 'العدد',
      idx_btn_kg: 'الوزن',
      idx_cal_calendars: 'التقويمات',
      idx_cal_dblclick: '· انقر مرتين لإضافة ملاحظة',
      idx_cal_legend: 'أيام بها أحداث',
      idx_cal_no_event: 'لا توجد أحداث',
      idx_cal_search: 'ابحث عن أحداث...',
      idx_cal_today: 'اليوم',
      idx_dow: ['إث','ثل','أر','خم','جم','سب','أح'],
      idx_ev_musteri: 'عميل',
      idx_ev_not: 'ملاحظة',
      idx_ev_personel: 'موظف',
      idx_ev_proje: 'مشروع',
      idx_grp_cikis: 'المراقبة والشحن',
      idx_grp_uretim: 'الإنتاج',
      idx_lbl_total_adet: 'إجمالي العدد',
      idx_lbl_total_kg: 'إجمالي الوزن',
      idx_loading: 'جاري التحميل...',
      idx_mat_alu: 'ألومنيوم',
      idx_mat_celik: 'فولاذ',
      idx_mat_cunife: 'كيونيفي',
      idx_mat_pas: 'ستانليس',
      idx_mat_tumu: 'الكل',
      idx_mo: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
      idx_spool_title: 'حالة البكرات في النظام',
      idx_stage_bekleyen: 'قيد الانتظار',
      idx_stage_imalat: 'التصنيع',
      idx_stage_kalite: 'الجودة',
      idx_stage_kaynak: 'اللحام',
      idx_stage_on_kontrol: 'الفحص المبدئي',
      idx_stage_sevke_hazir: 'جاهز للشحن',
      idx_stat_devre: 'الدوائر النشطة',
      idx_stat_kesim: 'قيد القطع',
      idx_stat_kk: 'قيد مراقبة الجودة',
      idx_stat_proje: 'المشاريع النشطة',
      idx_stat_sevk: 'شحنات هذا الشهر',
      idx_sys_label: 'نظام إدارة الحوض',
      idx_title: 'لوحة التحكم',
      kk_all: 'الكل',
      kk_approve_all: 'الموافقة على الكل',
      kk_breadcrumb: 'مراقبة الجودة',
      kk_btn_clear: 'مسح',
      kk_btn_create_invite: 'إنشاء حزمة دعوة',
      kk_cancel: 'إلغاء',
      kk_card_control: 'المراقبة:',
      kk_card_invite: 'الدعوة:',
      kk_contact_note: 'جهة الاتصال / ملاحظة',
      kk_control_date: 'تاريخ المراقبة المتوقع',
      kk_control_date_label: 'تاريخ المراقبة',
      kk_controller: 'المراقب',
      kk_create_save: 'إنشاء وحفظ الحزمة',
      kk_davet_circuit: 'دائرة:',
      kk_davet_spool: 'بكرة:',
      kk_davet_total: 'المجموع:',
      kk_decision: 'القرار',
      kk_durum_bekle: 'في انتظار الحوض',
      kk_durum_onay: 'موافق عليه',
      kk_durum_ret: 'مرفوض / تصحيح',
      kk_empty_bekle: 'لا توجد حزم دعوة معلقة',
      kk_empty_onay: 'لا توجد حزم موافق عليها بعد',
      kk_empty_spool: 'لا توجد بكرات للعرض',
      kk_enter_approval: 'إدخال الموافقة',
      kk_extra_note: 'ملاحظة إضافية',
      kk_filter_all_projects: 'جميع المشاريع',
      kk_filter_all_yards: 'جميع الأحواض',
      kk_filter_clear: 'مسح',
      kk_filter_proj: 'جميع المشاريع',
      kk_filter_yard: 'جميع الأحواض',
      kk_home: 'الرئيسية',
      kk_invite_date: 'تاريخ الدعوة',
      kk_mail: 'البريد الإلكتروني',
      kk_mail_optional: '(اختياري)',
      kk_modal_approve_title: 'إدخال موافقة الجودة',
      kk_modal_invite_title: 'إنشاء حزمة دعوة الجودة',
      kk_no_approved: 'لا توجد حزم موافق عليها بعد',
      kk_no_pending: 'لا توجد حزم دعوة معلقة',
      kk_no_spool: 'لا توجد بكرات للعرض',
      kk_optional: 'اختياري...',
      kk_pdf_btn: 'PDF',
      kk_pdf_preview: 'معاينة PDF',
      kk_reject: 'رفض / تصحيح',
      kk_reject_ph: 'أي بكرات رُفضت وما هو طلب التصحيح؟',
      kk_reject_reason: 'سبب الرفض',
      kk_save_approval: 'حفظ الموافقة',
      kk_search_ph: 'ابحث عن دائرة أو بكرة...',
      kk_sec_clear: 'مسح',
      kk_sec_create: 'إنشاء حزمة دعوة',
      kk_sec_devre: 'دائرة',
      kk_sec_kg: 'كجم',
      kk_sec_spool: 'بكرة',
      kk_secili: ' محدد',
      kk_select_all: 'تحديد الكل',
      kk_selected_spools: 'البكرات المحددة',
      kk_sevkiyata: 'إلى الشحن →',
      kk_spool_col: 'البكرة',
      kk_stat_approved: 'موافق عليه',
      kk_stat_bekle: 'في انتظار الحوض',
      kk_stat_davet: 'حزمة الدعوة',
      kk_stat_hazir: 'جاهز للجودة',
      kk_stat_invite: 'حزمة الدعوة',
      kk_stat_onay: 'موافق عليه',
      kk_stat_ready: 'جاهز للجودة',
      kk_stat_waiting: 'في انتظار الحوض',
      kk_status_approved: 'موافق عليه',
      kk_status_pending: 'في انتظار الحوض',
      kk_status_rejected: 'مرفوض / تصحيح',
      kk_tab_bekle: 'قيد الانتظار',
      kk_tab_bekleyen: 'قيد الانتظار',
      kk_tab_davet: 'إنشاء دعوة',
      kk_tab_onay: 'موافق عليه',
      kk_tab_onaylanan: 'موافق عليه',
      kk_title: 'مراقبة الجودة',
      kk_to_shipment: 'إلى الشحن →',
      kk_toast_approved_ship: 'موافق عليه — جاهز للشحن!',
      kk_toast_controller_req: 'اسم المراقب مطلوب',
      kk_toast_created: 'تم إنشاء حزمة الدعوة',
      kk_toast_date_req: 'التاريخ مطلوب',
      kk_toast_decision_req: 'يرجى تحديد قرار',
      kk_toast_invite_date_req: 'تاريخ الدعوة مطلوب',
      kk_toast_karar: 'يرجى تحديد قرار',
      kk_toast_kisi: 'اسم المراقب مطلوب',
      kk_toast_olusturuldu: 'تم إنشاء حزمة الدعوة',
      kk_toast_onaylandi: 'موافق عليه — جاهز للشحن!',
      kk_toast_pdf: 'جاري تنزيل PDF...',
      kk_toast_pdf_soon: 'معاينة PDF قريباً',
      kk_toast_reject_req: 'سبب الرفض مطلوب',
      kk_toast_rejected: 'مرفوض',
      kk_toast_ret_neden: 'سبب الرفض مطلوب',
      kk_toast_ret_sonuc: 'مرفوض',
      kk_toast_select_first: 'يرجى تحديد البكرات أولاً',
      kk_toast_sevkiyat: 'جاري تنزيل PDF...',
      kk_toast_shipment: 'تمت الإضافة إلى قائمة تحضير الشحن',
      kk_toast_tarih: 'التاريخ مطلوب',
      kk_tumu: 'الكل',
      kk_weight_col: 'الوزن',
      ks_at_least_one: 'يجب تحديد سجل واحد على الأقل',
      ks_breadcrumb: 'إدارة القطع',
      ks_btn_apply: 'تطبيق',
      ks_btn_clear: 'مسح',
      ks_btn_create: '📋 إنشاء قائمة قطع',
      ks_btn_form: '📂 نموذج القطع',
      ks_btn_markall: '☑ تحديد الكل',
      ks_btn_reset: '↺ إعادة',
      ks_btn_save_close: '✓ حفظ وإغلاق القائمة',
      ks_btn_unmarkall: '☐ إلغاء الكل',
      ks_chip_cap: 'القطر',
      ks_chip_cert: 'الشهادة',
      ks_chip_cert_no: 'غير موثق',
      ks_chip_cert_yes: 'موثق',
      ks_chip_grade: 'الجودة',
      ks_chip_isemir: 'أمر العمل',
      ks_chip_mat: 'المادة',
      ks_chip_search: 'بحث',
      ks_chip_thk: 'السماكة',
      ks_chip_yard: 'الحوض',
      ks_col_action: 'الإجراء',
      ks_col_cap: 'القطر',
      ks_col_cut: 'القطع (مم)',
      ks_col_cut_done: 'مقطوع',
      ks_col_grade: 'الجودة',
      ks_col_isemir: 'أمر العمل',
      ks_col_mat: 'المادة',
      ks_col_sert: 'شهادة',
      ks_col_spool: 'رقم البكرة',
      ks_col_spoolid: 'معرف البكرة',
      ks_col_thk: 'السماكة',
      ks_col_uca: 'الطرف A',
      ks_col_ucb: 'الطرف B',
      ks_col_yard: 'الحوض',
      ks_created: 'تم الإنشاء',
      ks_cut_label: 'مقطوع',
      ks_cut_progress: 'تقدم القطع',
      ks_done_header: '✓ قوائم مقطوعة',
      ks_downloaded: 'تم التنزيل',
      ks_empty_hint: 'غير معايير التصفية أو البحث',
      ks_empty_notfound: 'لا توجد سجلات',
      ks_excel_err: 'خطأ Excel:',
      ks_excel_ready: 'جاري تحضير Excel...',
      ks_filter_cert: 'الشهادة',
      ks_filter_cert_no: 'غير موثق',
      ks_filter_cert_yes: 'موثق',
      ks_filter_diam: 'القطر',
      ks_filter_grade: 'الجودة',
      ks_filter_isemir: 'أمر العمل',
      ks_filter_mat: 'المادة',
      ks_filter_thk: 'السماكة',
      ks_filter_yard: 'الحوض',
      ks_footer_boru: 'أنابيب · صفحة',
      ks_footer_total: 'المجموع:',
      ks_form_addstok: '+ إضافة مقطع أنبوب',
      ks_form_cancel: 'إلغاء',
      ks_form_kerf: 'هامش المنشار (مم)',
      ks_form_minartik: 'الحد الأدنى للبقايا (مم)',
      ks_form_parcaboru: 'أنابيب المقاطع المتوفرة — اختياري، مم',
      ks_form_run: '✂ إنشاء النموذج وتنزيله',
      ks_form_stok: 'طول المخزون القياسي (مم)',
      ks_form_trim: 'قص الطرف (مم)',
      ks_geri_dondu: 'عاد',
      ks_home: 'الرئيسية',
      ks_kesim_tamamlandi: 'اكتمل القطع',
      ks_kismi: 'جزئي',
      ks_lists_header: '📋 قوائم القطع',
      ks_modal_cut_btn: '✓ نعم، تم القطع',
      ks_modal_cut_cancel: 'إلغاء',
      ks_modal_cut_desc: 'سيتم إزالة هذا الأنبوب من القائمة ومعالجته.',
      ks_modal_cut_title: 'اكتمل القطع؟',
      ks_modal_list_cancel: 'إلغاء',
      ks_modal_list_cap: 'القطر:',
      ks_modal_list_create: '✓ إنشاء القائمة',
      ks_modal_list_hint: 'اتركه فارغاً للترقيم التلقائي.',
      ks_modal_list_mat: 'المادة:',
      ks_modal_list_no: 'رقم القائمة',
      ks_modal_list_title: '📋 إنشاء قائمة قطع',
      ks_modal_list_total: 'إجمالي القطع:',
      ks_modal_list_yard: 'الحوض:',
      ks_no_arc: 'لا توجد سجلات مكتملة بعد',
      ks_no_lists: 'لم يتم إنشاء قوائم قطع بعد',
      ks_no_lists_hint: 'أنشئ قائمة من تبويب قيد الانتظار',
      ks_no_single: 'لا توجد قطع فردية بعد',
      ks_page_title: '✂ إدارة القطع',
      ks_search_ph: 'رقم البكرة، أمر العمل، المادة...',
      ks_select_all: 'تحديد الكل',
      ks_single_header: '⚡ قطع فردية',
      ks_stat_filtered: 'مصفى',
      ks_stat_inlist: 'في القائمة',
      ks_stat_pending: 'إجمالي المنتظر',
      ks_tab_done: '✓ قوائم مقطوعة',
      ks_tab_lists: '📋 قوائم القطع',
      ks_tab_pending: '✂ قيد الانتظار',
      ks_tab_single: '⚡ قطع فردية',
      ks_tamamlandi: 'مكتمل',
      log_ara_placeholder: '🔍 بحث في العملية، المصدر، الوصف…',
      log_baslik: 'سجل العمليات',
      log_csv_indir: 'تنزيل CSV',
      log_csv_indirildi: 'تم تنزيل CSV',
      log_f_ay: 'هذا الشهر',
      log_f_bugun: 'اليوم',
      log_f_devre: '🔄 دائرة',
      log_f_giris: '🔐 تسجيل الدخول',
      log_f_hafta: 'هذا الأسبوع',
      log_f_is: '🔧 عمل',
      log_f_kk: '✅ مراقبة الجودة',
      log_f_sevk: '📦 الشحن',
      log_f_spool: '⚙️ Spool',
      log_f_tanim: '📋 تعريف',
      log_f_test: '🧪 اختبار',
      log_f_tum_islem: 'جميع العمليات',
      log_f_tum_zaman: 'كل الأوقات',
      log_gecmis: 'سجل العمليات',
      log_gorunum_tablo: 'جدول',
      log_gorunum_zaman: 'الجدول الزمني',
      log_il_devre_durdur: 'تم إيقاف الدائرة',
      log_il_giris: 'تسجيل الدخول',
      log_il_is_baslat: 'بدأ العمل',
      log_il_is_bitir: 'اكتمل العمل',
      log_il_kk_gonder: 'تم إرسال مراقبة الجودة',
      log_il_kk_onayla: 'تمت الموافقة على مراقبة الجودة',
      log_il_kk_red: 'رُفضت مراقبة الجودة',
      log_il_sevk: 'شحن',
      log_il_spool_durdur: 'تم إيقاف Spool',
      log_il_tanim_ekle: 'تمت إضافة التعريف',
      log_il_tanim_sil: 'تم حذف التعريف',
      log_il_kesim_tamamla: 'اكتمل القطع',
      log_il_kesim_eklendi: 'تمت إضافة القطع',
      log_il_kesim_liste: 'تم حفظ قائمة القطع',
      log_il_bukum_tamamla: 'اكتمل الانحناء',
      log_il_bukum_eklendi: 'تمت إضافة الانحناء',
      log_il_mrk_tamamla: 'اكتمل الترقيم',
      log_il_mrk_eklendi: 'تمت إضافة الترقيم',
      log_il_kk_davet: 'تم إنشاء دعوة مراقبة الجودة',
      log_il_kk_onay: 'تم حفظ موافقة مراقبة الجودة',
      ts_baslik: 'الاختبارات',
      ts_stat_bekleyen: 'قيد الانتظار', ts_stat_devam: 'جارٍ',
      ts_stat_tamamlanan: 'مكتمل', ts_stat_hatali: 'فاشل / إصلاح',
      ts_stat_toplam: 'إجمالي الحزم',
      ts_tab_bekleyen: 'قيد الانتظار', ts_tab_devam: 'جارٍ',
      ts_tab_tamamlanan: 'مكتمل', ts_tab_hepsi: 'جميع الاختبارات',
      ts_btn_yeni: 'اختبار جديد', ts_btn_sonuc: 'إدخال النتيجة',
      ts_f_tum_tip: 'جميع أنواع الاختبارات', ts_f_tum_tersane: 'جميع الأحواض',
      ts_ara_ph: 'رقم الاختبار، الدائرة، المشروع...',
      ts_modal_yeni: 'حزمة اختبار جديدة', ts_modal_sonuc: 'إدخال نتيجة الاختبار',
      ts_modal_tip: 'أنواع الاختبارات',
      ts_durum_bekleyen: 'في الانتظار', ts_durum_devam: 'جارٍ',
      ts_durum_tamamlandi: 'مكتمل ✓', ts_durum_hatali: 'فاشل / إصلاح',
      ts_kart_tarih: 'التاريخ:', ts_kart_yetkili: 'المسؤول:',
      ts_gecti: 'نجح', ts_hatali: 'فشل', ts_bekliyor: 'في الانتظار',
      ts_spool_sonuclari: 'نتائج البكرات',
      ts_bos: 'لا توجد اختبارات للعرض',
      ts_pdf_indir: 'جاري تنزيل PDF...',
      ts_toast_kod_ad: 'الرمز والاسم مطلوبان',
      ts_toast_kod_var: 'هذا الرمز موجود بالفعل',
      ts_toast_sonuc: ' تم حفظ نتيجة الاختبار',
      ts_toast_tip_eklendi: ' تمت إضافة نوع الاختبار',
      cmn_temizle: 'مسح',

      log_il_test_olustur: 'تم إنشاء الاختبار',
      log_il_test_sonuc: 'نتيجة الاختبار',
      log_kayit_bulunamadi: 'لا توجد سجلات',
      log_kayit_sayisi: ' سجل',
      log_stat_bugun: 'اليوم',
      log_stat_kullanici: 'المستخدمون',
      log_stat_tip: 'أنواع العمليات',
      log_stat_toplam: 'إجمالي السجلات',
      log_temizle: 'مسح السجل',
      log_temizle_onay: 'سيتم حذف جميع سجلات العمليات. هل أنت متأكد؟',
      log_temizlendi: 'تم مسح السجل',
      log_th_aciklama: 'الوصف',
      log_th_islem: 'العملية',
      log_th_kaynak: 'المصدر',
      log_th_kullanici: 'المستخدم',
      log_th_no: '#',
      log_th_zaman: 'الوقت',
      log_yenilendi: 'تم التحديث',
      mk_arc_header: '✓ القوائم المكتملة',
      mk_arc_title: 'الأرشيف',
      mk_at_least_one: 'يجب تحديد سجل واحد على الأقل',
      mk_breadcrumb: 'إدارة الوسم',
      mk_btn_apply: 'تطبيق',
      mk_btn_clear: 'مسح',
      mk_btn_create: '🏷 إنشاء قائمة وسم',
      mk_btn_excel: '📂 تنزيل Excel',
      mk_btn_markall: '☑ تحديد الكل',
      mk_btn_reset: '↺ إعادة',
      mk_btn_save_close: '✓ حفظ وإغلاق القائمة',
      mk_btn_unmarkall: '☐ إلغاء الكل',
      mk_chip_cap: 'القطر',
      mk_chip_isemir: 'أمر العمل',
      mk_chip_kalite: 'الجودة',
      mk_chip_parca: 'القطعة',
      mk_chip_search: 'بحث',
      mk_chip_tersane: 'الحوض',
      mk_col_action: 'الإجراء',
      mk_col_cap: 'القطر',
      mk_col_done: 'تم',
      mk_col_isemir: 'أمر العمل',
      mk_col_malzeme: 'المادة',
      mk_col_parca: 'اسم القطعة',
      mk_col_spool: 'رقم البكرة',
      mk_col_spoolid: 'معرف البكرة',
      mk_col_yard: 'الحوض',
      mk_created: 'تم الإنشاء',
      mk_empty_hint: 'غير معايير التصفية أو البحث',
      mk_empty_notfound: 'لا توجد سجلات',
      mk_filter_diam: 'القطر',
      mk_filter_grade: 'الجودة',
      mk_filter_isemir: 'أمر العمل',
      mk_filter_mat: 'المادة',
      mk_filter_parca: 'القطعة',
      mk_filter_yard: 'الحوض',
      mk_footer_record: 'سجلات · صفحة',
      mk_geri_dondu: 'عاد',
      mk_home: 'الرئيسية',
      mk_indirildi: 'تم التنزيل',
      mk_kismi: 'جزئي',
      mk_lists_header: '🗒 قوائم الوسم',
      mk_lists_title: 'القوائم المنشأة',
      mk_manuel_iptal: 'إلغاء',
      mk_manuel_title: 'الموسومة يدوياً',
      mk_marked: 'موسوم',
      mk_modal_list_cancel: 'إلغاء',
      mk_modal_list_cap: 'القطر:',
      mk_modal_list_create: '✓ إنشاء القائمة',
      mk_modal_list_hint: 'اتركه فارغاً للترقيم التلقائي.',
      mk_modal_list_kayit: 'السجلات:',
      mk_modal_list_no: 'رقم القائمة',
      mk_modal_list_parca: 'القطعة:',
      mk_modal_list_tersane: 'الحوض:',
      mk_modal_list_title: '🏷 إنشاء قائمة وسم',
      mk_modal_mark_btn: '✓ نعم، تم الوسم',
      mk_modal_mark_desc: 'هل تم وسم هذه القطعة يدوياً؟',
      mk_modal_mark_title: 'تحديد كموسوم',
      mk_modal_warn_desc: 'يجب أن تحتوي السجلات المحددة على نفس اسم القطعة والقطر.',
      mk_modal_warn_ok: 'موافق، سأصحح التصفية',
      mk_modal_warn_retry: 'أعد المحاولة بنفس المعايير',
      mk_modal_warn_title: 'لا يمكن إنشاء القائمة',
      mk_no_arc: 'لا توجد سجلات مكتملة بعد',
      mk_no_lists: 'لم يتم إنشاء قوائم وسم بعد',
      mk_page_title: '✂ إدارة الوسم',
      mk_plaka: 'لوحة',
      mk_progress_label: 'تقدم الوسم',
      mk_search_ph: 'رقم البكرة، أمر العمل، المادة...',
      mk_select_all: 'تحديد الكل',
      mk_serbest: 'وسم حر',
      mk_stat_filtered: 'مصفى',
      mk_stat_inlist: 'في القائمة',
      mk_stat_pending: 'إجمالي المنتظر',
      mk_tab_done: 'مكتمل',
      mk_tab_lists: 'قوائم الوسم',
      mk_tab_pending: 'في انتظار الوسم',
      mk_tamamlandi: 'مكتمل',
    }

    /* ── Yeni dil eklemek için ──────────────────────────────────
    fr: {
      cmn_anasayfa: 'Accueil',
      // ... diğer anahtarlar ...
    },
    ─────────────────────────────────────────────────────────── */
  };

  // ── Dil API'si ───────────────────────────────────────────────
  function getLang() {
    return document.documentElement.getAttribute('lang') ||
           localStorage.getItem('ares_lang') || 'tr';
  }

  function tv(key, fallback) {
    var lang = getLang();
    var dict = _LANG[lang];
    if (dict && dict[key] !== undefined) return dict[key];
    // 'tr' için ayrı dict olmasa da fallback kullan
    return fallback !== undefined ? fallback : key;
  }

  function applyI18n() {
    document.querySelectorAll('[data-i18n]').forEach(function(el) {
      var k = el.getAttribute('data-i18n');
      var isInp = el.tagName === 'INPUT' || el.tagName === 'TEXTAREA';
      if (!el.hasAttribute('data-i18n-tr'))
        el.setAttribute('data-i18n-tr', isInp ? el.placeholder : el.textContent.trim());
      var v = tv(k, el.getAttribute('data-i18n-tr'));
      if (isInp) { el.placeholder = v; } else { el.textContent = v; }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el) {
      var k = el.getAttribute('data-i18n-placeholder');
      if (!el.hasAttribute('data-i18n-ph-tr')) el.setAttribute('data-i18n-ph-tr', el.placeholder);
      el.placeholder = tv(k, el.getAttribute('data-i18n-ph-tr'));
    });
  }

  // ── MutationObserver — lang attribute değişince ──────────────
  new MutationObserver(function() {
    applyI18n();
    if (typeof window._onLangChange === 'function') window._onLangChange();
  }).observe(document.documentElement, { attributes: true, attributeFilter: ['lang'] });

  // ── Sayfa tarafından genişletme (opsiyonel) ──────────────────
  // ARES.lang.extend('fr', { my_key: 'ma valeur' });
  function extend(lang, keys) {
    if (!_LANG[lang]) _LANG[lang] = {};
    Object.assign(_LANG[lang], keys);
  }

  // ── Global export ────────────────────────────────────────────
  w.tv         = tv;
  w._applyI18n = applyI18n;
  w._getLang   = getLang;
  if (!w.ARES) w.ARES = {};
  w.ARES.lang  = { tv: tv, apply: applyI18n, extend: extend, getLang: getLang };

})(window);
